### ISSUE TITLE
Keep session after refresh

### ISSUE THREAD

**Issue by FredHasselot** [cloudspace/angular_devise#104]
Similare to this issue #17  (and many other posts) except i can't find any solution.

When i use login function it's fine and i look at the headers sent everything look right.

Access-Control-Allow-Credentials is set to true.
I can see cookies in the request header
and request payload contains my user.

i added this:

```
 angular.module('myModule', ['Devise'])
  .run(['Auth', function (Auth) {
    Auth.currentUser().then(function(user) {
      console.log(user);
      console.log(Auth._currentUser);
    });
  }]);
```

after login function i'm logged but when i refresh, Auth.currentUser() function  return an error.
and now, request payload contains an empty user.

i can see cookies in the resources tab of chrome developpers tools (XSRF-TOKEN and _back_session)

i'm lost here.

**Comment by agustinvinao** [comment]
Check in your angular app if you have this line in the config of the app: 

```
$httpProvider.defaults.withCredentials = true;
```

Thats send credentials on every request to the server in order to maintain credentials.

**Comment by FredHasselot** [comment]
Yes, i've got this line.
And i can see credentials in the request headers.

**Comment by FredHasselot** [comment]
It was a server issue.
I added this on rails.

```
allow do
    origins 'localhost:9000', '127.0.0.1:9000'
    resource '*',
    :headers => :any,
    :methods => [:get, :post, :delete, :put, :patch,  :head],
    :expose  => ['access-token', 'expiry', 'token-type', 'uid', 'client'],
    :max_age => 0
  end
```

Now the headers are not empty.
I also use localStorage.

**Comment by danielolivaresd** [comment]
@FredHasselot could you please elaborate on how you used localStorage?
