### ISSUE TITLE
How to share currentUser for all controller ?

### ISSUE THREAD

**Issue by khacluan** [cloudspace/angular_devise#33]
I have many controller  AboutCtrl, MainCtrl, UserCtrl.
I have written login code in UserCtrl , the Auth.isAuthenticated() only available in UserCtrl, but AboutCtrl and MainCtrl
How to share Auth.isAuthenticated() for all controllers ? or write a helper like devise helper user_sign_in?

**Comment by johnzw89** [comment]
Hi, I would like to know this as well

**Comment by jridgewell** [comment]
If you're sharing the same functionality between multiple controllers, that belongs in a Service (or Factor/Provider), not in the controller.
