### ISSUE TITLE
Auth.currentUser()

### ISSUE THREAD

**Issue by rightisleft** [cloudspace/angular_devise#36]
I'm paraphrasing from a few stackoverflow posts as it's unanswered and I have the same question:

http://stackoverflow.com/questions/27302932/getting-previous-session-using-angular-devise

I am using the cloudspace angularjs-devise library on the client. When I try to login/register I get a 200 ok response with the plain user object visible in the chrome js console. Refreshing the page seems to lose this information even though I assumed that the service would store this at some point since it also has logout and currentUser methods.

How do you recommend the rails api be setup to authenticate a post, with an empty user object, to the path defined at AuthProvider.loginPath

Is there a prefered method that uses a cookie, or simply passes in the rails current_user object? 

Please advise.

**Comment by fabianrios** [comment]
I'm using rack-cors gem and angular_rails_csrf gem but always getting this error
http://127.0.0.1:9000/users/sign_in.json 405 Method Not Allowed

**Comment by DCarper** [comment]
I was losing my session on refresh.. Setting defaults.withCredentials to true on the $http provider seemed to do the trick for me..

**Comment by Clempops** [comment]
I my case, on login, no cookies are written, as expected on refresh Auth.isAuthenticated() returns false. I am using a rails API

**Comment by alediniz** [comment]
Clempops 1+
