### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by fabianrios** [cloudspace/angular_devise#44]
Why the method is not allowed? I properly config my CORS, and disable any problems with all the services in my app but this one get not allowed all the time.

**Comment by jridgewell** [comment]
I'm going to need more information.

1. Did you add `respond_to :json` to `ApplicationController`?
2. Did you setup CSRF?
3. Are you using normal Devise?
4. What URL are you serving your angular app from?

**Comment by marksterxxx** [comment]
have you properly configured proxy to your rails server? you are sending post request to  your loginPath http://127.0.0.1:9000, 405 will happen if your js server only accepts GET request. try to set it to port 3000, if it works, your proxy isn't properly configured.

**Comment by fabianrios** [comment]
I was ignoring anything that isn't behind the "/api" prefix so I had to put devise also like this.
  scope '/api' do
      devise_for :users, controllers: { sessions: "users/sessions" }
  end

Thanks so much for the answers.
