### ISSUE TITLE
Recommended way to keep track of a User throughout app?

### ISSUE THREAD

**Issue by donpinkus** [cloudspace/angular_devise#46]
Right now at the top of every controller I have code that checks for a current user.  Is there a recommended way to set user once for a session, and access it whenever a controller needs it? 

```
myApp.controller('myPage', ['$scope', '$routeParams', 'Auth', function($scope, $routeParams, Auth){

  Auth.currentUser().then(function(user){
    // Set the current user
    $scope.user = user;
  }, function(error){
    $location.path('/');
  });
}]);
```

**Comment by marksterxxx** [comment]
I used a service
```javascript
myApp.factory('userService', function () {
    var userService = {};
    Auth.currentUser().then(function(user){
        userService.user = user;
    }, function(error){
    });
    return userService;
});
myApp.controller('myPage', function($scope,userService){
    $scope.userService = userService;
}
```

**Comment by bluengreen** [comment]
Couldn't you do this within a resolve on your routes too? 

```
when('/reports', {
            templateUrl: 'mytemplate.html',
            controller: 'myCtrl',
            resolve: { 
               currentUser: function(Auth){
                return Auth.currentUser();
              }
           }
```

**Comment by bartekupartek** [comment]
I'm seeking answer for this question and I've found [stackoverflow 1](http://stackoverflow.com/questions/29074185/how-to-globally-implement-authentication-with-angularjs-devise-and-ui-router), [stackoverflow 2](http://stackoverflow.com/questions/29423383/how-to-keep-globally-current-user-until-logout-with-angular-devise) without solution, so I am also looking for some example for angular devise.
