### ISSUE TITLE
Respond to Json

### ISSUE THREAD

**Issue by robypez** [cloudspace/angular_devise#48]
Hello, I'm creating a Ionic app for my Rails website and I need to authenticate with Devise.
In your docs you suggest to add "respond to_json" in application controller.

Is not better to add

```
config.to_prepare do
   DeviseController.respond_to :html, :json
end
```
 in application.rb as Devise suggest?

**Comment by jridgewell** [comment]
:+1: Want to open a PR to update the docs?

```ruby
# config/application.rb
module RailsApp
  class Application < Rails::Application
    # ...

    config.to_prepare do
      DeviseController.respond_to :html, :json
    end
  end
end
```
