### ISSUE TITLE
How can I update a user?

### ISSUE THREAD

**Issue by langersteff** [cloudspace/angular_devise#51]
Hey,

how can I update a user with angular devise? I want to change a users nickname (which is not the login-name)

Thanks in advance

**Comment by langersteff** [comment]
In case someone else needs it:

    $scope.saveUsername = function(userName, password) {
      $http.put('/users.json', {
        account_update: {name: userName},
        user: {name: userName, 'current_password': password}
      }).
      success(function(data, status, headers, config) {
        $log.debug("works", data);
      }).
      error(function(data, status, headers, config) {
        $log.debug("does not work", data);
      });
    }

And you also have to permit the parameter, in this case "name" in application_controller.rb
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:account_update) << :name
    end

**Comment by jridgewell** [comment]
This is best left to a User model. AngularDevise is just meant to authenticate your app with Devise, all authorizations and management are up to decide.

**Comment by magicalbanana** [comment]
@jridgewell +1
