### ISSUE TITLE
Angular_Devise and Grape Rails API

### ISSUE THREAD

**Issue by adamlove127** [cloudspace/angular_devise#52]
I've been trying to set up Angular_Devise with a rails grape api for controlling user login for an Ionic Application. 

The Api has a delete method in which the users session is ended by destroying the authentication token. I had great trouble configuring the logout method of Angular_Devise to work with my api as I couldn't pass any credentials, thus didn't have the authentication token of a user to identify them with. 

After a prolonged period attempting to create a solution this is what I have come up with:

In my controller:
```javascript
$scope.doLogout = function(){
    var credentials = {
      authentication_token: Auth._currentUser.authentication_token
    };

    Auth.logout(credentials).then(function(user) {
      console.log(user);
    });
  };
}])
```

In my app.js
```javascript
.config(function($httpProvider) {
  //$http.defaults.headers.common.Authorization = 'Basic YmVlcDpib29w'
  $httpProvider.defaults.headers.delete = { 'Content-Type' : 'application/json' };
})


.config(['AuthProvider', 'AuthInterceptProvider', function(AuthProvider, AuthInterceptProvider) {
    // Customize login
    var URL = "http://localhost:3000/api"
    AuthProvider.loginMethod('POST');
    AuthProvider.loginPath(URL + '/sessions');

    // Customize logout
    AuthProvider.logoutMethod('DELETE');
    AuthProvider.logoutPath(URL + '/sessions');

    // Customize register
    AuthProvider.registerMethod('POST');
    AuthProvider.registerPath(URL + '/users');

    // Customize the resource name data use namespaced under
    // Pass false to disable the namespace altogether.
    AuthProvider.resourceName(false);

    // Customize user parsing
    // NOTE: **MUST** return a truth-y expression
    AuthProvider.parse(function(response) {
        return response.data;
    });

    // Intercept 401 Unauthorized everywhere
    // Enables `devise:unauthorized` interceptor
    AuthInterceptProvider.interceptAuth(true);
}])
```

Then I changed the default logout in devise.js 
```javascript
logout: function(creds) {
                var returnOldUser = constant(service._currentUser);

                creds = creds || {};
                return $http(httpConfig('logout', creds))
                    .then(reset)
                    .then(returnOldUser)
                    .then(broadcast('logout'));
            
            },
```

It took me a very long time to figure out and I'm not sure it's the correct solution. 
Is this how I go about passing the authentication token when logging out?

**Comment by jridgewell** [comment]
Hmm, AngularDevise wasn't meant to be used with token based authentication. I don't see the harm in allow credentials to be passed to the `#logout` method, though. Want to open a PR?

**Comment by TheOneTheOnlyDavidBrown** [comment]
Closing since this issue is 11 months old, no PR has been created, and it wasn't intended for tokens. A good JSON web token (jwt) based authentication tool is [Satellizer](https://github.com/sahat/satellizer) for anyone looking for a token based approach over the cookie based approach of this package
