### ISSUE TITLE
how to get the current user variable?

### ISSUE THREAD

**Issue by folivi** [cloudspace/angular_devise#57]
Hi,
I need help on this.
I have a controller with this code
```coffeescript
@app
  .run ->
    console.debug 'angular still running!!'
  .controller 'authCtr', (Auth, $scope)->    
    $scope.user = null
    Auth.currentUser()
      .then (user)->
        $scope.user = user
        console.debug user
```
in my view I try to access the user variable but I get undefined. What am I doing wrong?
 I'm new with angular so my question my sound stupid, don't be too hard on me :)

**Comment by jridgewell** [comment]
`Auth.currentUser()` is an async method, returning a promise. You'll need to listen to changes to `$scope.user` so that when the promise resolves, your view will update.
