### ISSUE TITLE
Angular 1.4.0 is out, Angular-devise holding upgrade for rails-assets users

### ISSUE THREAD

**Issue by bopm** [cloudspace/angular_devise#58]
I can even offer PR, but as version number need to be bumped too, I prefer to ask authors for it.

**Comment by baberthal** [comment]
+1

**Comment by jridgewell** [comment]
I'll get it out this weekend.

**Comment by bopm** [comment]
@jridgewell any news on that?

**Comment by jridgewell** [comment]
Forgot about this waiting for #60. I just need to review that, and I'll push out tonight.

**Comment by bopm** [comment]
Yep, no problem. Just got feeling that it's something like that.

**Comment by jridgewell** [comment]
Closed with v1.1.

**Comment by bopm** [comment]
:+1:
