### ISSUE TITLE
Auth.login can't return credential errors when global interceptAuth is enabled

### ISSUE THREAD

**Issue by AmirKarimi** [cloudspace/angular_devise#59]
Devise returns 401 status for credentials errors (Ex. wrong password). I enabled interceptAuth globally which intercepts Auth.login calls as well that prevent my code to access the error result.

I think we should pass `interceptAuth=false` option to $http in Auth.login method.

**Comment by jridgewell** [comment]
That's the point of the [interceptor](https://github.com/cloudspace/angular_devise#interceptor).

**Comment by AmirKarimi** [comment]
As it mentioned we can disable interception using `interceptAuth: false` but what I say is that $http call which happened in Auth.login method should use this option to bypass interception. We don't need http interception in Auth.login. Right?

**Comment by jridgewell** [comment]
Oh, I see what you mean. Potentially, no. But, preventing interception on the login requests prevents you from catching a failed login attempt.

For example, what if the user tries to delete a record? If the user isn't authenticated, the intercepter catches. Now, a login popup appears, and the user mistypes the password. You can still intercept that to retry login, etc.

Want to whip up a PR that'll allow pass additional `$http` options to `#login`, `#logout`, and `#register`?

**Comment by AmirKarimi** [comment]
Yes I'll send a PR. Thanks

**Comment by AmirKarimi** [comment]
Should I update the version in `package.json` and `bower.json` and tag the version in git repo?
