### ISSUE TITLE
Username in registration

### ISSUE THREAD

**Issue by stoplion** [cloudspace/angular_devise#62]
I've added a userName to the Devise registration form. This works without Angular fine. Using `angular_devise` my form is sending the userName in the JSON request but it comes back `null`. Is there a way for `angular_devise` to handle this? The picking of a userName is done at the time of registration, not in a later step.

**Comment by zaccharier** [comment]
Hi ,

I just had the same issue using angular-devise with Ruby on Rails.
First you should have the attribute :username in your User model.
Then you should allow the :name atribute to be sent via this ``` protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end ``` added to the application_controller.rb 

Hope this helps.

**Comment by karensg** [comment]
Take a look at this post, they explain how to do it.
https://thinkster.io/angular-rails
