### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by AhmedZaleh** [cloudspace/angular_devise#64]
I'm trying to use Auth.login(credentials) to connect to a Rails API through Devise but it seems that the request does not get to the server. I get Status Code: 404 Not Found
 Request Method: POST
Request URL: localhost:3001/users/sign_in.json

also, in WEBrick terminal, I don't see any requests being made to the server.

**Comment by jridgewell** [comment]
Are you serving from `localhost:3001`?

**Comment by AhmedZaleh** [comment]
No, actually my API is on localhost:3000/ how can I set the base URL for angular_devise ?

**Comment by jridgewell** [comment]
See the [`AuthProvider`](https://github.com/cloudspace/angular_devise#authprovider) for customizing paths.
