### ISSUE TITLE
angular_devise + rails-api is vulnerable to CSRF attacks

### ISSUE THREAD

**Issue by aarongray** [cloudspace/angular_devise#69]
Because rails-api [strips out rails' CSRF protection](https://github.com/rails-api/rails-api/issues/150) - `protect_from_forgery` - [assuming that everyone using rails-api will use token authentication](https://github.com/rails-api/rails-api#for-already-existing-apps), and because angular_devise [relies on cookie authentication](https://github.com/cloudspace/angular_devise/issues/36#issuecomment-65709873), using rails-api with angular_devise means that you are vulnerable to CSRF. At the very least, it might be good to have a one-line comment in the angular_devise Readme section on CSRF making a clear warning to people, because rails-api is becoming very common, and has been [merged into Rails](https://github.com/rails/rails/pull/19832).

Please correct me if I'm wrong here, but I think this is a possible vulnerability worth highlighting.

**Comment by thelastinuit** [comment]
Oh dear!

I thought this was enough "Aditionally, if you have CSRF Forgery Protection enabled for your controller actions, you will also need to include the X-CSRF-TOKEN header with the token provided by rails. The easiest way to include this is to use the angular_rails_csrf gem."

So, @aarongray, I'm not well versed in the matter of CSRF, that gem is not enough? :/

**Comment by vfonic** [comment]
That gem is enough when the CSRF protection is ON. However, rails-api gem turns it off. I don't know what's the easiest way to turn it on for rails-api since I use full rails gem in my app which has it enabled.

**Comment by TheOneTheOnlyDavidBrown** [comment]
README.md regarding CSRF was updated in #63
