### ISSUE TITLE
Could not fetch specs from https://rails-assets.org/

### ISSUE THREAD

**Issue by ketan-ghumatkar** [cloudspace/angular_devise#70]
I have following code snippet in my Gemfile
```
source "https://rails-assets.org" do
  gem "rails-assets-angular-devise"
end
```

When I do ``` bundle install ``` on terminal to install dependencies, it give me  following error 
`Could not fetch specs from https://rails-assets.org/`

**Comment by bxt** [comment]
This is a temporary error due to the servers of rails-assets.org being down.

**Comment by Anyoks** [comment]
this is happening to me now. What do i do?

**Comment by hugoh59** [comment]
Happening again right now.

**Comment by p1v2** [comment]
It is happening again 😞

**Comment by SohanChy** [comment]
Yep, Its happening.

**Comment by yevgenko** [comment]
same problem today, internet works, but can't access https://rails-assets.org/ Connection refused
resolved by proxying via San Francisco data center, here is how:
https://gist.github.com/yevgenko/774b4835683d81e761e73eaae34cfe70

perhaps should contact railsassets on twitter :)

**Comment by xeruf** [comment]
See also https://github.com/tenex/rails-assets/issues/292, https://github.com/tenex/rails-assets/issues/471, https://github.com/tenex/rails-assets/issues/472
