### ISSUE TITLE
[Feature Request] Update user functionality

### ISSUE THREAD

**Issue by karensg** [cloudspace/angular_devise#73]
Hi guys,

It would be nice if the framework would support the update User functionality. This is the only thing I am missing in this great library. Or am I wrong?

Cheers,
Karens

**Comment by ouranos** [comment]
I'd like this too. There's an open pull request #24

Could we get this merged? I'm happy to help with the conflicts if that's needed.

**Comment by TheOneTheOnlyDavidBrown** [comment]
closed in #74 (which was rebased off of #24)
