### ISSUE TITLE
Remember Me?

### ISSUE THREAD

**Issue by voltechs** [cloudspace/angular_devise#75]
How do we handle Remember Me functionality?

**Comment by tyronewilson** [comment]
+1

**Comment by sinr0202** [comment]
in credentials object, add remember_me: 1 or 0.

**Comment by cyb-prajaktac** [comment]
@sinr0202 shall i do this only at front end ?
Nothing needed from backend.?

**Comment by sinr0202** [comment]
@cyb-prajaktac front end only. the backend is irrelevant to angular

**Comment by TheOneTheOnlyDavidBrown** [comment]
per @sinr0202's suggestion you should add remember_me to the credentials object (in this example it's user) like so:
<input type="checkbox" name="user[remember_me]" value="1" checked="checked" />
