### ISSUE TITLE
Directory name creates bugs with require path in application.js

### ISSUE THREAD

**Issue by fschueller** [cloudspace/angular_devise#77]
Hi,
when adding angular-devise to a Rails project via bower 

```bower install --save angular-devise```,

as laid down in the documentation, it gets added to the vendor/assets/bower-components directory as "AngularDevise" and in bower.json as something like

```"AngularDevise": "angular-devise#~1.1.0"```

When requiring the file in application.js as

```//= require angular-devise```

and hitting localhost:3000, it throws an error, telling me the file could not be found. I was only able to fix this by renaming the folder to "angular-devise" and putting down

```"angular-devise": "~1.1.0"```

in the bower.json dependencies, which solved this error. 

(Please keep in mind I'm "just" at the beginner/intermediate level in Rails and a total newbie to Angular, so I don't know if it's really a bug or I just messed up somewhere else)

**Comment by julianorinyol** [comment]
I had the same issue. Changing my bower.json to "angular-devise": ..    fixed it.    
but then I read the readme for angular-devise, it says to require it like so:
 
//= require angular-devise/lib/devise

so for me this was an issue with thinkster.io angular rails tutorial i was following, misinforming me,  not this gem

**Comment by hienvd** [comment]
I have the same problem. Which is the right way to require it?
