### ISSUE TITLE
Forgot password ?

### ISSUE THREAD

**Issue by FredHasselot** [cloudspace/angular_devise#81]
Hi,

How about the password reset devise function ?
(forgotten password)

Thanks

**Comment by Sergezdv** [comment]
+1

**Comment by ronakjain90** [comment]
I see that it's implemented, but it's not been released.

**Comment by Sergezdv** [comment]
@ronakjain90 Thanks, but i dont find this. can you give link?

**Comment by TheOneTheOnlyDavidBrown** [comment]
added in #74 and released in v1.2.0
