### ISSUE TITLE
Change of host for url calls

### ISSUE THREAD

**Issue by azranel** [cloudspace/angular_devise#90]
Is there a way to change backend host for which every call is made? My situation is that I have different server for frontend and different server for backend. Backend server is on `3000` port and frontend app is on `9000` port.

**Comment by TheOneTheOnlyDavidBrown** [comment]
Short answer is no you cannot pass in the base url or port. But I think this is a good idea and should be included. I'm welcome to PRs if anyone has modified it to allow setting the base url

**Comment by TheOneTheOnlyDavidBrown** [comment]
@azranel I put up a PR for this. If you could check it to make sure it works on your end before I merge it, that would be very helpful

**Comment by david-buildcloud** [comment]
Apologies for the basic question.

I was wondering if it'd be possible to get an example of how to set this config option correctly. I've tried the following with no luck :(

```
.config(function(AuthProvider) {
  AuthProvider.baseUrl("http://localhost:3000");
})
```
