### ISSUE TITLE
TypeError: AuthProvider.baseUrl is not a function

### ISSUE THREAD

**Issue by AliceOJJm** [cloudspace/angular_devise#98]
Trying to set base url in following way:

angular.module('mymodule', [ 'ui-notification', 'ngTagsInput', 'angular-loading-bar', 'ui.router', 'ui.bootstrap', 'templates', 'Devise', 'ngFileUpload', 'xeditable', 'bootstrapLightbox']).
    config(function(AuthProvider, AuthInterceptProvider) {
        AuthProvider.baseUrl('http://localhost:2000');
    });

Getting:
TypeError: AuthProvider.baseUrl is not a function

 alert(Object.keys(AuthProvider)) doesn't contain it either.

**Comment by danielolivaresd** [comment]
Having same issue

**Comment by pcasa** [comment]
+1

Looks like src/auth.js has function, but not lib/devise.js.  Updated build not checked in?

**Comment by nitzanav** [comment]
+1

**Comment by ryan-on-rails** [comment]
I was able to get this working by adding the code from src/auth.js into lib/devise.js.

However, another tweak is needed because the baseUrl is not being utilized in the httpConfig function. Here is a snippet that will work properly once you add the extra code from src/auth.js. I will get a pr up for this as well since it's such a minor change.

```
function httpConfig(action, data, additionalConfig) {
  var url = baseUrl + paths[action];
  var config = {
      method: methods[action].toLowerCase(),
      url: url
  };

  if (data) {
     if (resourceName) {
        config.data = {};
        config.data[resourceName] = data;
      } else {
          config.data = data;
      }
  }

  angular.extend(config, additionalConfig);
  return config;
}
```

**Comment by ryan-on-rails** [comment]
Created a pull request to address this issue:
#107

**Comment by rockandruby** [comment]
Still doesn't work

**Comment by gustavogsimas** [comment]
Why is this still not working?

**Comment by ryan-on-rails** [comment]
Not sure who is maintaining this now. There are several prs that are even older than the one I submitted for this ticket 🤕

**Comment by lioneljingles** [comment]
+1

**Comment by Victorgf87** [comment]
May be a bit late, but I think it's still on time.
It looks like the method is gone, can't understand why, but I just found a solution:
`AuthProvider.loginPath("https://localhost:3000"+AuthProvider.loginPath())`
You just have to do the same thing with the other methods (I hope it will work the same way)
